### ISSUE TITLE
Documentation for GITHUB_TOKEN required permissions

### ISSUE THREAD

**Issue by bogdannazarenko** [HeRoMo/pronto-action#119]
When default org level permissions as set to readonly for GITHUB_TOKEN, what required [permissions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions) are required for this Action in a workflows?

Please update documentation accordingly.

Thank you.

**Comment by HeRoMo** [comment]
Thank you, I updated README.md.
